### ISSUE TITLE
可以加人3个英文搜索吗？

### ISSUE THREAD

**Issue by ericvlog** [Xwudao/hunhepan-pc#4]
bitsearch.to

https://bt4gprx.com/

https://www.btdig.com/

谢谢

**Comment by Xwudao** [comment]
pc规则还是安卓端规则，我发现需要代理访问，对于 其它人来说意义不大

**Comment by ericvlog** [comment]
因为国内有时很难找到国外资源。

所有的都需要代理吗？

你的软件应该也有很多国外的用户吧？ 我就是在国外的。。。呵呵

**Comment by Xwudao** [comment]
> 因为国内有时很难找到国外资源。
> 
> 所有的都需要代理吗？

安卓端还是PC端？现在PC端不怎么维护了

**Comment by ericvlog** [comment]
> > 因为国内有时很难找到国外资源。
> > 
> > 所有的都需要代理吗？
> 
> 安卓端还是PC端？现在PC端不怎么维护了

那就安卓版好了，两个版本我都有，我以为规则是通用的。
谢谢

**Comment by Xwudao** [comment]
> > > 因为国内有时很难找到国外资源。
> > > 所有的都需要代理吗？
> > 
> > 
> > 安卓端还是PC端？现在PC端不怎么维护了
> 
> 那就安卓版好了，两个版本我都有，我以为规则是通用的。 谢谢

有空加上吧

**Comment by ericvlog** [comment]
> > > > 因为国内有时很难找到国外资源。
> > > > 所有的都需要代理吗？
> > > 
> > > 
> > > 安卓端还是PC端？现在PC端不怎么维护了
> > 
> > 那就安卓版好了，两个版本我都有，我以为规则是通用的。 谢谢
> 
> 有空加上吧

👍，当2你加上了，安卓那里自动更新吗。

**Comment by Xwudao** [comment]
前2个已添加，安装端重新导入就行；第三个无法添加

**Comment by ericvlog** [comment]
> 前2个已添加，安装端重新导入就行；第三个无法添加

谢谢啊，太感谢了。
