### ISSUE TITLE
开放API能用吗？

### ISSUE THREAD

**Issue by erikhuang** [Xwudao/hunhepan-pc#5]
如题
根据下面的文档，调用api无法获取数据
http://127.0.0.1/v1/runner/search 接口也报错

https://docs.hunhepan.com/api-docs.html
### search disk
POST https://hunhepan.com/open/search/disk
Content-Type: application/json

{
  "q": "搜索词",
  "page": 1,
  "size": 10,
  "time": "",
  "type": "",
  "exact": true
}

**Comment by Xwudao** [comment]
下面的文档，已经给了完整的请求API域名与URL，并不和你认为的127一样
